{% set name = "proto-plus" %}
{% set version = "1.22.1" %}
{% set sha256 = "6c7dfd122dfef8019ff654746be4f5b1d9c80bba787fe9611b508dd88be3a2fa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proto-plus-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<36]
  # noarch: python
  script: python -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - protobuf >=3.19.0,<5.0.0dev

test:
  requires:
    - pip
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check

about:
  home: https://github.com/googleapis/proto-plus-python
  summary: Beautiful, Pythonic protocol buffers.
  description: |
    This is a wrapper around protocol buffers. Protocol buffers is a specification
    format for APIs, such as those inside Google. This library provides protocol
    buffer message classes and objects that largely behave like native Python types.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/googleapis/proto-plus-python
  doc_source_url: https://github.com/googleapis/proto-plus-python/tree/main/docs
  doc_url: https://proto-plus-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - tswast
