{% set name = "proto-plus" %}
{% set version = "1.27.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 912a7460446625b792f6448bade9e55cd4e41e6ac10e27009ef71a7f317fa147

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - protobuf >=3.19.0,<7.0.0

test:
  source_files:
    - tests
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - pytz
    - google-api-core >=1.31.5

about:
  home: https://github.com/googleapis/proto-plus-python
  summary: Beautiful, Pythonic protocol buffers.
  description: |
    This is a wrapper around protocol buffers. Protocol buffers is a specification
    format for APIs, such as those inside Google. This library provides protocol
    buffer message classes and objects that largely behave like native Python types.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/googleapis/proto-plus-python
  doc_url: https://googleapis.dev/python/proto-plus/latest

extra:
  recipe-maintainers:
    - tswast
