{% set name = "proto-plus" %}
{% set version = "1.20.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proto-plus-{{ version }}.tar.gz
  sha256: be7eb221f8b9e035c6622eca77cf341000edc8039676d027598f81318ef8faea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - protobuf >=3.19.0
    - python >=3.6

test:
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check
  requires:
    - pip
    - python <3.10

about:
  home: https://github.com/googleapis/proto-plus-python.git
  summary: Beautiful, Pythonic protocol buffers.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/googleapis/proto-plus-python
  doc_url: https://proto-plus-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - tswast
