{% set name = "proto-plus" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 6e93d5f5ca267b54300880fff156b6a3386b3fa3f43b1da62e680fc0c586ef22

build:
  number: 0
  skip: true  # [py<37]
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - protobuf >=3.19.0,<6.0.0
  run_constrained:
    - google-api-core >=1.31.5

test:
  source_files:
    - tests
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest
    - pytz
    - google-api-core >=1.31.5

about:
  home: https://github.com/googleapis/proto-plus-python
  summary: Beautiful, Pythonic protocol buffers.
  description: |
    This is a wrapper around protocol buffers. Protocol buffers is a specification
    format for APIs, such as those inside Google. This library provides protocol
    buffer message classes and objects that largely behave like native Python types.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/googleapis/proto-plus-python
  doc_url: https://proto-plus-python.readthedocs.io

extra:
  recipe-maintainers:
    - tswast
