{% set name = "proto-plus" %}
{% set version = "1.24.0" %}
{% set sha256 = "30b72a5ecafe4406b0d339db35b56c4059064e69227b8c3bda7462397f966445" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proto-plus-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py<37]
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - protobuf >=3.19.0,<6.0.0dev

test:
  requires:
    - pip
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check

about:
  home: https://github.com/googleapis/proto-plus-python
  summary: Beautiful, Pythonic protocol buffers.
  description: |
    This is a wrapper around protocol buffers. Protocol buffers is a specification
    format for APIs, such as those inside Google. This library provides protocol
    buffer message classes and objects that largely behave like native Python types.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/googleapis/proto-plus-python
  doc_url: https://proto-plus-python.readthedocs.io

extra:
  recipe-maintainers:
    - tswast
